hmcts/vh-booking-queue-subscriber

BookingQueueSubscriber/BookingQueueSubscriber.Common/ApiHelper/ApiUriFactory.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriberFunction.cs, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/VideoServiceTokenHandler.cs
[VIH-4702](https://tools.hmcts.net/jira/browse/VIH-4702)
invalid delete conference uri corrected
```
[ ] Yes
[x] No
```
=> Change debug to info logging and fix incorrect delete uri

BookingQueueSubscriber/BookingQueueSubscriber.Common/ApiHelper/ApiRequestHelper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApiService.cs
[VIH-4800](https://tools.hmcts.net/jira/browse/VIH-4800)
Deserialise conference response using snake case strategy
```
[ ] Yes
[x] No
```
=> Safely deserialise using snake case naming strategy

BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/HearingDetailsUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToBookConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingDetailsUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingReadyForVideoHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/BookNewConferenceRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/UpdateConferenceRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingDetailsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingReadyForVideoHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-5450
```
[ ] Yes
[ ] No
```
=> VIH-5450: Adding hearing venue name

azure-pipelines.yml
N/a
Update trigger for release and hotfix branch
```
[ ] Yes
[ x] No
```
=> Update trigger for release and hotfix branch

BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToBookConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToUpdateConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingCancelledHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingDetailsUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingReadyForVideoHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantsAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/BookNewConferenceRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/UpdateConferenceRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunction/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToUpdateConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingReadyForVideoHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriberFunction.cs, azure-pipelines.yml
VIH-5747
Add audio recording value to integration events
```
[ ] Yes
[x] No
```
=> VIH-5747 add audio recording to hearing integration events

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs
https://tools.hmcts.net/jira/browse/VIH-5851
- added observer and panel member
```
[ ] Yes
[x] No
```
=> VIH-5851 VH_Officer_adds_Additional_Participant_to_booking

BookingQueueSubscriber/BookingQueueSubscriber.Common/ApiHelper/ApiUriFactory.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/EndpointRemovedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/EndpointUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointRemovedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointRemovedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointUpdatedHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-6312
=> VIH-6312 Change endpoints to take sip instead of endpoint id

BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/ParticipantRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs
VIH-6488
* add hearing role to participant dtos for video api requests
```
[ ] Yes
[x] No
```
=> VIH-6488 add hearing role to participant dtos for video api requests

BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/EndpointUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/EndpointToRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/EndpointDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/AddEndpointRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/UpdateEndpointRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunction/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointUpdatedHandlerTests.cs
VIH-6463
* add defence advocate to EndpointUpdatedHandler.cs and EndpointAddedHandler.cs
```
[ ] Yes
[x] No
```
=> VIH-6463 Add defence advocate to Endpoint handlers

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs
https://tools.hmcts.net/jira/browse/VIH-6580
Added to CaseRoleGroup enum Applellant and State
```
[ ] Yes
[ ] No
```
=> VIH-6580 added to case role group enum appellant and state

CODEOWNERS, azure-pipelines.yml
VIH-6594
* update pipeline
```
[ ] Yes
[x] No
```
=> VIH-6594 update pipeline

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/BookHearingRequestBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/HearingParticipantsBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Data/HearingData.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Data/RoleData.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/HearingsSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/ParticipantSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/TestsBase.cs, azure-pipelines.release.yml
- https://tools.hmcts.net/jira/browse/VIH-6669
- Added CACD hearing test
- Fixed an issue with the release yml
```
[ ] Yes
[X] No
```
=> VIH-6669 Added CACD hearing type tests

azure-pipelines.release.yml
- Renamed Services to VhServices in the release.yml
```
[ ] Yes
[X] No
```
=> VIH-5255 Fix for release issue

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Data/RoleData.cs
https://tools.hmcts.net/jira/browse/VIH-6643
- Change hearing role names
```
[ ] Yes
[X] No
```
=> VIH-6643 Change hearing role names

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Data/RoleData.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunction/RunTests.cs
https://tools.hmcts.net/jira/browse/VIH-6640
Rename hearing roles
```
[ ] Yes
[ x] No
```
=> VIH-6640 Rename hearing roles

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs
https://tools.hmcts.net/jira/browse/VIH-6738
=> VIH-6738 immigration_homeoffice_casetype

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/BookHearingRequestBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/HearingParticipantsBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/HearingsSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/ParticipantSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/Verify.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services.BookingsApi/BookingsApiClient.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services.VideoApi/VideoApiClient.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantRemovedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/Contracts/UpdateParticipantRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/ParticipantResponse.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunction/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/MessageHandlerTestBase.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs
VIH-6172
Update ParticipantUpdatedHandler.cs to include username
```
[ ] Yes
[x] No
```
=> VIH-6172 Update ParticipantUpdatedHandler.cs to include username

BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs
VIH-6637
Fix DI container setup
```
[ ] Yes
[x] No
```
=> VIH-6637 Fix DI container setup

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Hooks/Setup.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/parameters.runsettings, azure-pipelines.release.yml
https://tools.hmcts.net/jira/browse/VIH-7058
- Enabling local test environment switching
```
[ ] Yes
[X] No
```
=> VIH-7058 Local Test Environment Switching

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/ConfigLoader.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/Dockerfile, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
VIH-7174
Add new configuration provider for SDS
```
[ ] Yes
[x] No
```
=> VIH-7174 Add new configuration provider for SDS

.gitignore, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/MessageHandlerTestBase.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, azure-pipelines.release.yml, azure-pipelines.yml
VIH-6162
Update release configuration in yaml
```
[ ] Yes
[x] No
```
=> VIH-6162 update release pipeline configuration

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Hooks/Setup.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/appsettings.json, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/AzureAdConfiguration.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/ServicesConfiguration.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/Security/AzureTokenProvider.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/AzureTokenProviderTests.cs, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/appsettings.json
VIH-6162
* Hardcode auth rather than rely on unreliable config
```
[ ] Yes
[x] No
```
=> VIH-6162 update pipeline

azure-pipelines.nightly.yml
- Added Overnight BQS Pipeline
```
[ ] Yes
[X] No
```
=> VIH-5552 Added Overnight BQS Pipeline

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Helpers/DateListMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/HearingsSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/ParticipantSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/TestsBase.cs
- Added test for multi day hearings
```
[ ] Yes
[X] No
```
=> VIH-7255 Added test for multi day hearings

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/BookHearingRequestBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/HearingsSubscriberTests.cs
- Move scheduled date for multi day tests at weekends
```
[ ] Yes
[X] No
```
=> VIH-7255 Move scheduled date for multi day tests at weekends

BookingQueueSubscriber/.dockerignore, BookingQueueSubscriber/nuget.config
VIH-7174
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=29280&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a
```
[ ] Yes
[X] No
```
=> VIH-7174 added nuget config

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/BookHearingRequestBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/HearingParticipantsBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Builders/LinkedParticipantsRequestBuilder.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Configuration/Data/RoleData.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Hooks/Setup.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/HearingsSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/ParticipantSubscriberTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/Tests/Verify.cs, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/ServicesConfiguration.cs, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-6958
- Updated acceptance tests with linkedparticipant scenario
```
[ ] Yes
[x] No
```
=> VIH-6958 updated acceptance tests with linkedparticipants

BookingQueueSubscriber/BookingQueueSubscriber/Dockerfile
VIH-7337
set runtime versions
https://hmctsreform.visualstudio.com/VirtualHearings/_build/results?buildId=30558&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a
```
[ ] Yes
[x] No
```
=> VIH-7337 set runtime versions

azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-7660
replaced PAT for AZDO 
```
[ ] Yes
[X] No
```
=> VIH-7660 - updated PAT

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/HearingParticipantsUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingParticipantsUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/MessageHandlerTestBase.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://github.com/hmcts/vh-video-api/pull/393
Implemented a new message event which is published from the Bookings API, which the subscriber picks up and forwards to the Video API.
```
[ ] Yes
[ x ] No
```
=> VIH-7766 Participants not linking sometimes when editing a hearing

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/ServicesConfiguration.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingParticipantsUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantsAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/IVideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/MessageHandlerTestBase.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/VideoWebTokenHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, azure-pipelines.nightly.yml, azure-pipelines.release.yml, azure-pipelines.yml
VIH-7558
Call VideoWeb as well as VideoApi when Participants are updated. Updating VideoApi nuget package. This requires an update to VideoWeb for this to call.
```
[x] Yes
[] No
```
=> VIH-7558 update participants lists UI

azure-pipelines.release.yml
N/A
Fixed env pipeline changes
```
[ ] Yes
[X] No
```
=> VIH-7558 pipeline remediation

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Consts/UserRoleName.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8036
Update videoApi.Client to include StaffMember in the booking confirmation logic
```
[ ] Yes
[X] No
```
=> VIH-8036 VHO confirms booking with Staff Member

azure-pipelines.release.yml
N/A
Fixed var groups
```
[ ] Yes
[X] No
```
=> VIH-7946 removed the preprod group from non-prod setting

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingReadyForVideoHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/IVideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingReadyForVideoHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoApiServiceTests/BookNewConferenceTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoWebServiceTests/PushNewConferenceAddedTests.cs
https://tools.hmcts.net/jira/browse/VIH-8254
updated implementation for updated implementation for hearing ready for video handler event to call a new internal event in video web
**Does this PR introduce a breaking change?** 
```
[ ] Yes
[x] No
```
=> VIH-8254 updated implementation for hearing ready for video handler event

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, azure-pipelines.yml
https://tools.hmcts.net/jira/browse/VIH-8703
```
[ ] Yes
[x ] No
```
=> VIH-8703 Reference bookings api casetype group enum

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8733
- Updated bookingsApi.Client package to version 1.30.11
```
[ ] Yes
[x] No
```
=> VIH-8733 Updated bookingsApi.Client package to version 1.30.11

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
- https://tools.hmcts.net/jira/browse/VIH-8567
- updated bookings api reference
```
[ ] Yes
[x] No
```
=> VIH-8567 updated bookings api reference

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8803
- updated package reference for bookings api
```
[ ] Yes
[x] No
```
=> VIH-8803 updated package reference for bookings api client

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8803
- updated package ref for bookings api
```
[ ] Yes
[x] No
```
=> VIH-8803 updated nuget package reference for bookings api

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-8804
updated BookingApi package to reflect new changes to the case Type
=> VIH-8804 - updated nuget package

azure-pipelines.release.yml
Release pipeline should trigger off the CI pipeline like other in VH
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Add enabled for CI trigger

charts/vh-booking-queue-subscriber/Chart.yaml
VIH-9021
update from beta version to release version
```
[ ] Yes
[ ] No
```
=> VIH-9021 - update from beta version to release version

BookingQueueSubscriber/BookingQueueSubscriber/Dockerfile, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, azure-pipelines.sds.pr-close.yml, azure-pipelines.sds.pr-release.yml, azure-pipelines.sds.release.yml, charts/vh-booking-queue-subscriber/Chart.yaml, charts/vh-booking-queue-subscriber/values.dev.template.yaml, charts/vh-booking-queue-subscriber/values.yaml
remove GitVersion from Dockerfile
```
[ ] Yes
[ ] No
```
=> VIH-9999 - remove GitVersion from Dockerfile

BookingQueueSubscriber/BookingQueueSubscriber.Common/Security/AzureTokenProvider.cs, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, azure-pipelines.sds.pr-release.yml
amend mount name for KV.
```
[ ] Yes
[ x ] No
```
=> VIH-9999 - Amend Booking Queue

azure-pipelines.sds.pr-release.yml
VIH-9236
SonarCloud fix
```
[ ] Yes
[ x ] No
```
=> VIH-9236 - SonarCloud fix

BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/JudgeUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/JudgeUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/JudgeUpdatedHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-9230
Add event handler to process judge detail being updated
```
[ ] Yes
[X] No
```
=> VIH-9230 notify when judge contact email sent

BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/JudgeUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/JudgeUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/JudgeUpdatedHandlerTests.cs
https://tools.hmcts.net/jira/browse/VIH-9230
```
[ ] Yes
[X] No
```
=> VIH-9230 Refactored JudgeUpdate event handler to only send notification email when contact email changed

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/FeatureToggles.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserApi/UserService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/CreateAndNotifyUserHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, azure-pipelines.release.yml, azure-pipelines.yml, charts/vh-booking-queue-subscriber/Chart.yaml, charts/vh-booking-queue-subscriber/values.yaml
https://tools.hmcts.net/jira/browse/VIH-9259
- Adds Launch Darkly SDK and service
- If the SSPR feature is enabled, adds new users to the SSPR Enabled AAD group so that they can reset their own password
```
[ ] Yes
[x] No
```
=> VIH-9259 Add new users to SSPR group when SSPR feature enabled

azure-pipelines.sds.pr-release.yml
VIH-9532 - Amend PR Release Pipeline
VIH-9532 - Amend PR Release Pipeline
```
[ ] Yes
[ x ] No
```
=> VIH-9532 - Amend PR Release Pipeline

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, azure-pipelines.release.yml
[VIH-9557](https://tools.hmcts.net/jira/browse/VIH-9557)
```
[ ] Yes
[X] No
```
=> VIH-9557 Updated yaml and csproj azure function version

BookingQueueSubscriber/BookingQueueSubscriber.Services/UserCreationAndNotification.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/UserCreationAndNotificationTests.cs
Update username even if the user already exists as the data in test environments databases is not consistent
```
[ ] Yes
[x ] No
```
=> VIH-9633 update username

.github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPO-12024
Limit renovate to helm
```
[ ] Yes
[x] No
```
=> VIH-0000 - DtSPO-12024 - update renovate config

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/VideoWebTokenHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
VIH-9679
Update api clients to receive deserialised error messages
```
[ ] Yes
[x] No
```
=> VIH-9679 Update api clients to receive deserialised error messages

BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/BookingQueueSubscriber.AcceptanceTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.AcceptanceTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/AllocationHearingsIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/AllocationHearingHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingAllocationDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/IVideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/AllocationHearingHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoWebServiceTests/PushAllocationToCsoUpdatedMessageTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriberFunction.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/test.json
https://tools.hmcts.net/jira/browse/VIH-9391
added allocation IM integration
=> VIH-9391 - added allocation IM integration

charts/vh-booking-queue-subscriber/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPO-12091
Update dependencies to latest version
New image that gets created will be tested on a single cluster to check all is working
```
[ ] Yes
[x] No
```
=> VIH-0000 - update chart and deps

.github/CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-9753
Add vh-qa team as codeowners
```
[ ] Yes
[x] No
```
=> VIH-9753 Update CODEOWNERS

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/UpdateConferenceEndpointsRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotificationServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserApi/UserServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/IVideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriber.UnitTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointDefenceAdvocateHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoApiServiceTests/GetEndpointsForConferenceTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoWebServiceTests/PushEndpointsUpdatedMessageTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-9696
1. Created UpdateConferenceEndpointsRequest class
2. Add PushEndpointsUpdatedMessage to the video web service
3. Added PushEndpointsUpdatedMessage from video web to the add endpoint to conference
4. Added PushEndpointsUpdatedMessage from video web to the update endpoint in conference
5. Exposed the GetEndpointsForConference call from the video api
6. Added tests
```
[ ] Yes
[x] No
```
=> VIH-9696 - Add an endpoint to a hearing at the last minute

.github/CODEOWNERS
https://tools.hmcts.net/jira/browse/VIH-10016
Update so all code changes need vh and vh-qa & so that devops approve the pipeline files and the .github folder
```
[ ] Yes
[x] No
```
=> VIH-10016 update-codeowner-file

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/FeatureToggles.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/Configuration/FeatureTogglesClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/AddNotificationRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotificationService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotificationServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotifyParams.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserCreationAndNotification.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/AddNotificationRequestMapperTest.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/CreateAndNotifyUserHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/NotificationServiceTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/UserCreationAndNotificationTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-9844
* When the new template toggle is on, new Individuals will get a welcome email as well as a new account details email
```
[ ] Yes
[x] No
```
=> VIH-9844 toggle new user template

BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ServiceProviderFactory.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/appsettings.json, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, azure-pipelines.yml, charts/vh-booking-queue-subscriber/Chart.yaml, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9972
- Replace instrumentation key with connection string
```
[ ] Yes
[x] No
```
=> VIH-9972 Update app insights

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10087
Updates clients for the new case role group
```
[ ] Yes
[x] No
```
=> VIH-10087 Add new case type for Chester Crime Pathfinder

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Extensions/ParticipantDtoExtensions.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/JudgeUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10090
- Pass in the user role, hearing role and case type group when updating participants so that we can modify a participant's role for the update JOH endpoint
```
[ ] Yes
[x] No
```
=> VIH-10090 Update JOH in the booking

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantsAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriber.UnitTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriberFunction.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
VIH-10112
Add logging to Handler and Web Service
```
[ ] Yes
[x] No
```
=> VIH-10112 Add logging to Handler and Web Service

charts/vh-booking-queue-subscriber/Chart.yaml, charts/vh-booking-queue-subscriber/values.yaml
https://tools.hmcts.net/jira/browse/VIH-10005
PlatOps are reporting that there is over 3TB per month of logs generated by VH, need to reduce pod logging
=> VIH-10005 Reduce logging

BookingQueueSubscriber/BookingQueueSubscriber.Services/DateExtensions.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingReadyForVideoHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotificationServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserCreationAndNotification.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/HearingIsReadyForVideoIntegrationMessageTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, charts/vh-booking-queue-subscriber/values.dev.template.yaml
[VIH-10204](https://tools.hmcts.net/jira/browse/VIH-10204)
=> VIH-10204 - send notification to representative

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToBookConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-9570
Pass Case Type Service Id to Video API, for use in the filename
=> VIH-9570 New audio recording filename for HRS

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/NotificationApi/NotificationService.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/NotificationServiceTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/UserCreationAndNotificationTests.cs
VIH-10022
Remove dependency on obsolete feature flag endpoint
=> VIH-10022 Remove dependency on obsolete feature flag endpoint

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingAmendmentNotificationHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, charts/vh-booking-queue-subscriber/values.dev.template.yaml
[VIH-10353](https://tools.hmcts.net/jira/browse/VIH-10353)
=> VIH-10353 - Admin web Unable to sent notifications for Edit hearings

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/ParticipantUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserApi/UserService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserApi/UserServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/UserServiceTests/UpdateUserContactEmailTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-10490
=> VIH-10490 Change update user account endpoint to optionally update contact email

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriber.UnitTests.csproj, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
https://tools.hmcts.net/jira/browse/VIH-10125
https://tools.hmcts.net/jira/browse/VIH-10706
This is needed to fix pipeline failures, as the nuget package versions currently being referenced no longer exist in the library
=> VIH-10125 Use latest api client packages

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/NewParticipantMultidayHearingConfirmationHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, charts/vh-booking-queue-subscriber/values.dev.template.yaml
Added update participant name on videoapi to multi-day new participant handler
=> VIH-10793 Multiday new users unable to join the hearing

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToBookConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/VideoSupplier.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/HearingReadyForVideoHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingReadyForVideoHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-10807
update BQS to include the conference supplier
=> VIH-10807 update BQS to include the conference supplier

azure-pipelines.sds.master-release.yml, variables/test.yaml
See [VIH-10983](https://tools.hmcts.net/jira/browse/VIH-10983)
Refactor non-prod master release pipeline to allow separate image build & ad-hoc deploy to specific environments.
Tested that pipeline works as expected, and images are built and pushed with the relevant tag.
=> VIH-10983 refactor non-prod master deployment pipeline

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/GlobalUsings.cs, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, README.md, docker-compose.override.yml, setup-secrets.sh
VIH-10993
* reload on config change for secret by file
* Remove deprecated VH.Core.Configuration
=> VIH-10993 reload on config change for secret by file

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/GlobalUsings.cs, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, README.md, docker-compose.override.yml, setup-secrets.sh
VIH-10993
Update implementation of reading key per file to reload on change
* [`setup-secrets.sh`](diffhunk://#diff-88e533a6137b5f19e2a62de2352166591ce7df23addbdaeb598055e889ad3c1aR1-R77): Added a new script to set up secrets by extracting values from a YAML file and storing them in a specified directory.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L17-R38): Added instructions for running the app as a container and using Docker Compose.
=> VIH-10993 reload config on change

azure-pipelines.sds.master-release.yml
VIH-10843
This pull request introduces a new CI build stage to the `azure-pipelines.sds.master-release.yml` file. The changes include setting up variables, defining the build and test jobs, and configuring SonarQube properties.
* Added a new `CI_Build` stage with no dependencies and a display name "Test & Sonar". (`azure-pipelines.sds.master-release.yml`)
=> VIH-10843 add unit test and sonar analysis to master build

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/EndpointUpdatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToBookConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ConferenceRole.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ConferenceRoomType.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/EndpointDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointAddedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/EndpointUpdatedHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/HearingToBookConferenceMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/EndpointAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
VIH-10697
This pull request introduces new enums and properties to handle conference roles and room types.
* Updated `BookingsApi.Client` to 2.3.9
* Updated `NotificationApi.Client` to 2.3.4
* Updated `VideoApi.Client` to 2.2.28
* Introduced `ConferenceRole` and `ConferenceRoomType` enums in `BookingQueueSubscriber.Services/MessageHandlers/Dtos`. 
* Added `Role` property to `EndpointDto` and `ConferenceRoomType` property to `HearingDto`.
=> VIH-10697 map screening requirements to room and and role

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/HearingToUpdateConferenceMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json
VIH-11042
* Map the`RoomType` for `UpdateConferenceRequest.cs` in `HearingDetailsUpdatedHandler.cs`
=> VIH-11042 Map the RoomType for HearingDetailsUpdatedHandler

azure-pipelines.sds.master-release.yml, variables/demo.yaml
See VIH-11181](https://tools.hmcts.net/jira/browse/VIH-11181)
enable demo image and helm build & push
=> VIH-11181 enable demo image and helm buildpush

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/CreateAndNotifyUserHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/NewParticipantHearingConfirmationHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/NewParticipantMultidayHearingConfirmationHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/CreateAndNotifyUserHandlerTests.cs, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-11176
Push a message to video web when a participant's username is updated. This will then trigger an update of the conference cache
=> VIH-11176 Message video web when username is updated

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingsApiClientFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/ParticipantDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-10899
* Upgrade API clients to ensure none of the V1 operations or models are still used
* Hard-code case type group with the value "Obsolete". Video API still requires a value but does not return it in any models and video web has removed its usage entirely
=> VIH-10899 upgrade API clients

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/VideoSupplier.cs, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-11197
- Remove vodafone feature toggle
- Remove and replace references to Kinly
=> VIH-11197 Remove Vodafone toggle and Kinly supplier

.github/workflows/launch-darkly-find-code-refs-in-pr.yml, .github/workflows/launch-darkly-flag-sync.yml, .github/workflows/osv-scanner-pr.yml
VIH-11246
Update to the GitHub Actions:
* Switch the full LD code scan to run against master only and on a schedule
* Add the LD code scan on diff to run against PRs only
* Turn off fail on vuln for OSV scanner
=> VIH-11246 Update GH Actions

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-11248
Remove deprecated packages
Drop support for netstandard2.1
Minimum version is net6.0
Automation Tests
=> VIH-11248 remove deprecated packages 

BookingQueueSubscriber/BookingQueueSubscriber.Common/BookingQueueSubscriber.Common.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Common/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/AllocationHearingsIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/IntegrationEvents/HearingsAllocatedIntegrationEvent.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/AllocationHearingHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/HearingAllocationDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/JusticeUserDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/IVideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoApi/VideoApiServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/IVideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/Models/HearingAllocationNotificationRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebService.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/VideoWebServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/AllocationHearingHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/MessageHandlerTestBase.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoWebServiceTests/PushAllocationToCsoUpdatedMessageTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
VIH-9762
refactor cso allocation
=> VIH-9762 refactor cso allocation

BookingQueueSubscriber/BookingQueueSubscriber.Common/Logging/FakeLogger.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/UserApi/UserServiceFake.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber/Startup.cs
https://tools.hmcts.net/jira/browse/VIH-10358
- Add assertions on the requests sent to notification api
- Add extra test coverage
- Add FakeLogger - needed for DI for the JudgeUpdatedHandler
=> VIH-10358 Update tests to assert on the notification requests

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10558
=> VIH-10558 user-api package update

BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/AllocationHearingHandler.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/MessageHandlers/Dtos/JusticeUserDto.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/VideoWeb/Models/HearingAllocationNotificationRequest.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/BookingQueueSubscriberFunctionTests/RunTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/AllocationHearingHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/VideoWebServiceTests/PushAllocationToCsoUpdatedMessageTests.cs
VIH-11301
VIH-11269
provide the justice name in the allocation update to avoid additional api calls in video web to get the display name
=> VIH-11301 include allocation name

BookingQueueSubscriber/BookingQueueSubscriber.Services/BookingQueueSubscriber.Services.csproj, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToParticipantRequestMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/Mappers/ParticipantToUpdateParticipantMapper.cs, BookingQueueSubscriber/BookingQueueSubscriber.Services/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/Mappers/ParticipantToUpdateParticipantRequestMapperTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/HearingParticipantsUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantUpdatedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/MessageHandlers/ParticipantsAddedHandlerTests.cs, BookingQueueSubscriber/BookingQueueSubscriber.UnitTests/packages.lock.json, BookingQueueSubscriber/BookingQueueSubscriber/BookingQueueSubscriber.csproj, BookingQueueSubscriber/BookingQueueSubscriber/packages.lock.json, charts/vh-booking-queue-subscriber/values.dev.template.yaml
https://tools.hmcts.net/jira/browse/VIH-10794
=> VIH-10794 Update api client

.github/workflows/close-pr.yml
VIH-11409 
Update close-pr action to use correct branch var
=> VIH-11409 Update close-pr action to use correct branch var
